id: AF650DCCE
title: 'Making Great Bliss the Path: Visualisation and Mantra Recitation of Medicine
  Buddha'
type: translation
pechas:
- ICCB9AE15
- I14050811
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:46:49.695604
  last_modified_at: 2023-01-04 11:46:49.695618
  collections:
  - Dudjom Lingpa Series
  - Works of Tibetan Masters
alignment_to_base:
  ICCB9AE15/23AA: CD33
  I14050811/FF78: CD33
